### ISSUE TITLE
About M:N and work stealing 

### ISSUE THREAD

**Issue by liliang-cn** [cutajarj/ConcurrentProgrammingWithGo#3]
1. This is wrong:
<img width="1320" alt="image" src="https://github.com/cutajarj/ConcurrentProgrammingWithGo/assets/20553741/02528f69-9609-43ef-906c-128d7e5637db">
M means kernel level thread and N means goroutines.

2. This one is confusing:
<img width="1434" alt="image" src="https://github.com/cutajarj/ConcurrentProgrammingWithGo/assets/20553741/0067e874-d291-43a3-8941-6965feebbe2c">
When a goroutine is blocked, go will not create a new kernel thread.

**Comment by cutajarj2** [comment]
Hi Leo,
Thank you for purchasing the book.

1. "M:N hybrid threading"
Different text books use different notations/naming. For example the popular book "Operating System Concepts" by Abraham Silberschatz, refers to the threading models as One to One, Many to One and Many to Many. On the left the author is referring to the user-level threads (goroutines) and the kernel-level threads on the right, i.e. User-level threads to kernel-level threads. This notation is common and used in other textbooks as well.

Similarly in this book I use the notation is X:Y is referring X mapped onto Y. 
For M:N it's saying M user-level threads mapped onto N kernel-level threads. 
For N:1 it's saying N user-level threads mapped onto 1 kernel-level thread.
Just like the book mentioned before, the left of the notation is the number of user-level threads while on the right it's the number of kernel-level threads. Hence using this notation, the description given in my book is correct.

2. "Go creating a new kernel thread."
Goroutine can be blocked (resulting in the entire kernel-level thread being blocked), by a blocking call (such as blocking IO). In such cases the go runtime moves any goroutines, currently mapped on that kernel-level thread, onto a "new" non-blocked kernel-level thread.
Whether it creates a new kernel-level thread or re-uses an existing one depends on the scenario of the execution and the implementation of the runtime. Think, for example, of a case where all existing kernel-level threads are blocked but there are still goroutines that can execute without blocking. In such cases the runtime doesn't have any choice but to create a new kernel-level thread if it wants to execute the remaining goroutines.

**Comment by liliang-cn** [comment]
Thank you for the clear and patient explanation.
