### ISSUE TITLE
in chapter9 fade-out fade-in pattern is url load balance?

### ISSUE THREAD

**Issue by yuforlong** [cutajarj/ConcurrentProgrammingWithGo#6]
Hi, it's a good book for me to study go concurrent programming.

But in chapter9 ,fade-out fade-in pattern, it said make url load balance for downloads.

I only saw used many times for same urls channel. 

```go
       urls := generateUrls(quit)
	pages := make([]<-chan string, downloaders)

	for i := 0; i < downloaders; i++ {
		pages[i] = downloadPages(quit, urls)
	}

```

downloadPages param urls is same for times. 

If I understand incorrectly, look forward to reply

**Comment by cutajarj** [comment]
Hi there,
The Fan-out concurrency pattern is when multiple goroutines read from the same channel. In this way, we can distribute the work among a set of goroutines.

As an analogy you can think of a single queue of people wanting to buy a train ticket using multiple ticket machines. In this analogy the urls single channel is the queue of people, and the multiple _downloadPages()_  goroutines are the multiple ticket machines.
The _downloadPages()_ goroutines will load balance the messages between them, just like the ticket machines will load balance the people needing to buy tickets.

Hope this helps you understand this pattern.

**Comment by yuforlong** [comment]
Thank you for your reply.

I really need to think again, my understanding of load balancing may be multiple downloadPages, processing the load on the same URLs Queue . That is, each downloadPage is taken from an unprocessed URL for processing.

**Comment by yuforlong** [comment]
I understand where my understanding error lies. I mistakenly thought that URLs were of type list, but in reality they are a channel.

Since it is a channel, each DownloadPage is equivalent to attempting to retrieve content from URLs together, thus achieving load balancing.

I'm really sorry. It's taking up your time. Wishing you a happy life!
